# Site settings
title: "Fabius Lihanda Achevi"
email: fabiuslihandaachevi@gmail.com
description: >-
  Portfolio website of Fabius Lihanda — Cybersecurity Analyst, Data Scientist, and Python Web Developer.
  Passionate about securing digital systems, analyzing data, and building web solutions.
baseurl: "" # leave blank if using GitHub Pages with username.github.io
url: "https://lihandafabius.github.io" # your GitHub Pages URL
twitter_username: lihanda_fabius
github_username: lihandafabius
minimal_mistakes_skin: dark # ✨ Set to dark theme
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Nairobi

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author settings
author:
  name   : "Fabius Lihanda Achevi"
  avatar : "/assets/images/WhatsApp Image 2025-04-07 at 14.26.08.jpeg" # Place your avatar in this path
  bio    : "Cybersecurity Analyst | Data Scientist | Python Web Developer"
  location : "Nairobi, Kenya"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/fabius-lihanda-228947241/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lihandafabius"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:fabiuslihandaachevi@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/lihanda_fabius"

# Footer links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/fabius-lihanda-228947241/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lihandafabius"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:fabiuslihandaachevi@gmail.com"

# Defaults for layout
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: splash
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
