# Site settings
title: "Fabius Lihanda | Cybersecurity Analyst & DevOps Engineer"
email: fabiuslihandaachevi@gmail.com
description: >-
  Cybersecurity Analyst & DevOps Engineer specializing in threat detection, 
  cloud security, infrastructure automation, and secure application development.
baseurl: ""
url: "https://lihandafabius.github.io"
twitter_username: lihanda_fabius
github_username: lihandafabius
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Nairobi

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author settings
author:
  name   : "Fabius Lihanda Achevi"
  avatar : "/assets/images/bio-photo.jpg" # Consider a professional headshot
  bio    : "Cybersecurity Analyst | DevOps Engineer | Cloud Security Specialist"
  location : "Nairobi, Kenya"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/fabius-lihanda-228947241/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lihandafabius"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:fabiuslihandaachevi@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/lihanda_fabius"
    - label: "Resume"
      icon: "fas fa-fw fa-file-pdf"
      url: "/assets/documents/resume.pdf"

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Certifications"
    url: /certifications/
  - title: "Skills"
    url: /skills/
  - title: "Blog"
    url: /blog/
  - title: "Contact"
    url: /contact/

# Footer links
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/fabius-lihanda-228947241/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lihandafabius"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:fabiuslihandaachevi@gmail.com"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
